version: "0.1"
environments:
  - name: main
    branch: main
    mode: pull-request
apps:
  - name: next-with-translation
    path: ""
    text-resources:
      - path: public/locales/*/common.json
        format: nested-key-value
